id: ec4fcded89e847c0ac4e45f3d5c6c1a2
initial_creation_type: ocr
source_metadata:
  volumes:
    1ddb475abe754c0ab30e39f64946e038:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
